- id: add-jira-ticket
  name: Add Jira Ticket
  description: This hook adds Jira ticket name to the commit message.
  language: docker
  entry: java -jar app-standalone.jar
  require_serial: true
  stages:
    - prepare-commit-msg
    - pre-commit