version: 2.1

orbs:
  python: circleci/python@3.0.0

parameters:
  clojure-version:
    type: string
    default: '1.11.1'
  python-version:
    type: string
    default: '3.12.8'
  pre-commit-version:
    type: string
    default: '4.0.1'

executors:
  clojure:
    docker:
      - image: 'cimg/clojure:<< pipeline.parameters.clojure-version >>'

commands:
  install-pre-commit:
    steps:
      - run: echo 'pre-commit==<< pipeline.parameters.pre-commit-version >>' > requirements.txt
      - python/install-packages:
          pkg-manager: pip

jobs:
  lint:
    executor: clojure
    steps:
      - checkout
      - run: lein clj-kondo
      - run: lein zprint -c src/**/*.clj test/**/*.clj project.clj
  # TODO: store tests results
  test_unit:
    executor: clojure
    steps:
      - checkout
      - run: lein test
  test_e2e:
    machine:
      image: ubuntu-2204:2022.04.2
    resource_class: medium
    steps:
      - checkout
      - install-pre-commit
      - run:
          name: Run end-to-end tests
          command: ./e2e-test.sh
  # build_image: TODO

workflows:
  version: 2
  lint_test:
    jobs:
      - lint
      - test_unit:
          requires:
            - lint
      - test_e2e:
          requires:
            - lint
